import { AiFillPrinter, AiOutlineAudioMuted } from 'react-icons/ai';
import {
BiNetworkChart,
BiSolidCabinet,
BiSolidCctv,
BiSolidStoreAlt
} from 'react-icons/bi';
import {
BsGrid1X2Fill,
BsPersonLinesFill,
BsPersonStanding,
BsPersonVideo3
} from 'react-icons/bs';
import { CgCommunity } from 'react-icons/cg';
import {
  FaBatteryThreeQuarters,
  FaCamera,
  FaChalkboardTeacher,
  FaCoffee,
  FaDog,
  FaEthernet,
  FaFireExtinguisher,
  FaHeadphones,
  FaIdCard,
  FaKey,
  FaLock,
  FaMicrophone,
  FaMotorcycle,
  FaNetworkWired,
  FaPaintBrush,
  FaParking,
  FaPhone,
  FaPlug,
  FaShower,
  FaThermometerEmpty,
  FaToilet,
  FaTools,
  FaWheelchair,
  FaVolumeMute
} from 'react-icons/fa';
import {
  FaGlassWaterDroplet,
  FaLocationCrosshairs,
  FaSquareParking,
  FaTrainSubway,
  FaVanShuttle
} from 'react-icons/fa6';
import { GiNightSleep } from 'react-icons/gi';
import {
GrBraille,
GrLounge,
GrWorkshop,
GrYoga
} from 'react-icons/gr';
import { ImBooks, ImExit } from 'react-icons/im';
import { IoIosPeople, IoMdEye } from 'react-icons/io';
import {
  IoBarbellSharp,
  IoCardSharp,
  IoShareSocialSharp,
  IoVolumeLowSharp,
  IoWater
} from 'react-icons/io5';
import {
  MdAir,
  MdCable,
  MdCleaningServices,
  MdCoPresent,
  MdDirectionsBike,
  MdDocumentScanner,
  MdFastfood,
  MdGrass,
  MdLocalBar,
  MdLocalCafe,
  MdLocalPolice,
  MdMeetingRoom,
  MdMoreTime,
  MdNoFood,
  MdNoiseControlOff,
  MdOutgoingMail,
  MdOutlineDoNotDisturbOnTotalSilence,
  MdOutlineLocalLaundryService,
  MdOutlineNetworkWifi3Bar,
  MdOutlinePets,
  MdOutlineSecurity,
  MdOutlineSmartDisplay,
  MdOutlineSmokeFree,
  MdOutlineVpnLock,
  MdOutlineWbTwilight,
  MdPassword,
  MdRememberMe,
  MdRestaurant,
  MdRoomPreferences,
  MdSettingsInputHdmi,
  MdWifiTethering,
  MdWorkspacesOutline
} from 'react-icons/md';
import {
  PiBowlSteamFill,
  PiCigaretteFill,
  PiCoinVerticalFill,
  PiDeskFill,
  PiDressFill,
  PiElevatorFill,
  PiLockersFill,
  PiOfficeChairFill,
  PiTreeEvergreenFill
} from 'react-icons/pi';
import {
  RiBattery2ChargeFill,
  RiBilliardsFill,
  RiFingerprintFill,
  RiFridgeFill,
  RiPrinterFill,
  RiProjector2Fill,
  RiReservedFill,
  RiSofaFill,
  RiTeamFill,
  RiTvFill
} from 'react-icons/ri';
import {
  TbAirConditioning,
  TbAlarmSmoke,
  TbArrowRampLeft,
  TbChargingPileFilled,
  TbMicrowaveFilled,
  TbPackages,
  TbStackFront,
  TbToolsKitchen2
} from 'react-icons/tb';
import { SiTablecheck } from 'react-icons/si';

export const AMENITY_ICON_MAPPINGS: Record<string, any> = {
  showers: FaShower,
  meeting_rooms: MdMeetingRoom,
  laundry_service: MdOutlineLocalLaundryService,
  outdoor_seating: MdGrass,
  bike_racks: MdDirectionsBike,
  braille_signage: GrBraille,
  telephone_booths: FaPhone,
  noise_controlled_area: FaVolumeMute,
  skill_sharing_sessions: BsPersonVideo3,
  restrooms: FaToilet,
  board_games: RiBilliardsFill,
  shared_tables: IoShareSocialSharp,
  lounge_area: GrLounge,
  yoga_classes: GrYoga,
  workshops: GrWorkshop,
  huddle_room: CgCommunity,
  community_board: IoIosPeople,
  air_purifier: MdAir,
  water_refill_station: IoWater,
  vending_machine: PiCoinVerticalFill,
  networking_events: BiNetworkChart,
  charging_station: BiNetworkChart,
  smoke_detector: TbAlarmSmoke,
  tv_monitor: RiTvFill,
  emergency_exits: ImExit,
  pantry: BiSolidCabinet,
  workshop_area: FaTools,
  team_room: RiTeamFill,
  quiet_hours: IoVolumeLowSharp,
  member_discounts: MdRememberMe,
  smoking_area: PiCigaretteFill,
  shuttle_service: FaVanShuttle,
  scanner: MdDocumentScanner,
  conference_room: MdRoomPreferences,
  natural_light: MdOutlineWbTwilight,
  lockers: PiLockersFill,
  package_receiving: TbPackages,
  front_desk_reception: BsPersonLinesFill,
  printer: AiFillPrinter,
  smart_lockers: FaKey,
  temperature_control: FaThermometerEmpty,
  guest_wifi: MdOutlineNetworkWifi3Bar,
  free_coffee: FaCoffee,
  event_space: MdWorkspacesOutline,
  microwave: TbMicrowaveFilled,
  breakout_room: BsGrid1X2Fill,
  sari_sari_store: BiSolidStoreAlt,
  on_site_barista: MdLocalBar,
  water_dispenser: FaGlassWaterDroplet,
  extension_cords: FaPlug,
  whiteboard: FaChalkboardTeacher,
  backup_power: FaBatteryThreeQuarters,
  social_events: FaNetworkWired,
  private_office: FaLock,
  fire_extinguisher: FaFireExtinguisher,
  wired_ethernet_ports: FaEthernet,
  after_hours_security: MdOutlineSecurity,
  quiet_zone: AiOutlineAudioMuted,
  charging_ports: RiBattery2ChargeFill,
  free_parking: FaParking,
  refrigerator: RiFridgeFill,
  cctv_in_common_areas: BiSolidCctv,
  free_tea: PiBowlSteamFill,
  biometric_entry: RiFingerprintFill,
  smartboard: MdOutlineSmartDisplay,
  nap_room: GiNightSleep,
  soundproof: MdOutlineDoNotDisturbOnTotalSilence,
  mesh_wifi_coverage: MdCable,
  dedicated_static_ip: FaLocationCrosshairs,
  vpn_friendly_network: MdOutlineVpnLock,
  mail_handling: MdOutgoingMail,
  no_pets_allowed: MdOutlinePets,
  overtime_allowed: MdMoreTime,
  library_books: ImBooks,
  pet_friendly: FaDog,
  on_site_restaurant: MdRestaurant,
  no_smoking_indoors: MdOutlineSmokeFree,
  wheelchair_accessible_restrooms: FaWheelchair,
  cleaning_services: MdCleaningServices,
  loyalty_rewards: IoCardSharp,
  usb_ca_charging_hubs: TbChargingPileFilled,
  noise_free: MdNoiseControlOff,
  ramps: TbArrowRampLeft,
  sofa_lounge_setting: RiSofaFill,
  elevators: PiElevatorFill,
  reserved_parking: RiReservedFill,
  visitors_allowed: IoMdEye,
  air_conditioned: TbAirConditioning,
  wheelchair_accessible_entrance: FaWheelchair,
  food_drinks_not_allowed: MdNoFood,
  microphone: FaMicrophone,
  hdmi_cables_adapters: MdSettingsInputHdmi,
  photography: FaCamera,
  security_guard: MdLocalPolice,
  photocopier: RiPrinterFill,
  motorcyle_parking: FaMotorcycle,
  rooftop_area: TbStackFront,
  paid_snacks: MdFastfood,
  smart_lock_access: MdPassword,
  nearby_public_transport: FaTrainSubway,
  dedicated_desk: PiDeskFill,
  standing_desk: BsPersonStanding,
  art_displays: FaPaintBrush,
  fitness_area_gym: IoBarbellSharp,
  presentation_area: MdCoPresent,
  headsets: FaHeadphones,
  ergonomic_chair: PiOfficeChairFill,
  keycard_access: FaIdCard,
  onsite_cafe: MdLocalCafe,
  paid_parking: FaSquareParking,
  projector: RiProjector2Fill,
  kitchenette: TbToolsKitchen2,
  hot_desk: SiTablecheck,
  highspeed_wifi: MdWifiTethering,
  plants_greenery: PiTreeEvergreenFill,
  changing_room: PiDressFill,
};
